# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
        ('courses', '0002_loginreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_courses', to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='loginReg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='loginreg',
            name='user_creator',
        ),
        migrations.DeleteModel(
            name='LoginReg',
        ),
    ]
